import React, { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../api.js';
export default function Studio() {
  const { id } = useParams(); const [project, setProject] = useState(null); const [selected, setSelected] = useState(0); const [text, setText] = useState(''); const [rendering, setRendering] = useState(false);
  const load = () => api(`/projects/${id}`).then(p => { setProject(p); setText(p.scenes?.[selected]?.text || ''); }); useEffect(load, [id]);
  if (!project) return <div className="loading">Загрузка студии…</div>;
  const scene = project.scenes?.[selected]; const select = i => { setSelected(i); setText(project.scenes[i]?.text || ''); };
  async function save() { const p = await api(`/projects/${id}/scenes/${scene.id}`, { method: 'PATCH', body: JSON.stringify({ text }) }); setProject(p); }
  async function render() { await save(); setRendering(true); await api(`/projects/${id}/run?from=download`, { method: 'POST' }); const timer = setInterval(async () => { const p = await api(`/projects/${id}`); setProject(p); if (p.status === 'ready' || p.status === 'edited') { clearInterval(timer); setRendering(false); } }, 1000); }
  const media = scene?.pick;
  return <div className="studio-page"><div className="studio-top"><Link to="/" className="back">← Все проекты</Link><div><p className="eyebrow">СТУДИЯ</p><h1>{project.title}</h1></div><div className="studio-actions">{project.render && <a href={project.render.url} download className="ghost">Скачать MP4 ↓</a>}<button className="primary" onClick={render} disabled={rendering}>{rendering ? 'Рендер…' : 'Рендер видео →'}</button></div></div><div className="studio-grid"><aside className="scene-list"><h3>Сцены <span>{project.scenes.length}</span></h3>{project.scenes.map((s, i) => <button className={selected === i ? 'scene active' : 'scene'} key={s.id} onClick={() => select(i)}><span>{String(i + 1).padStart(2, '0')}</span><div>{s.text}<small>{((s.endMs - s.startMs) / 1000).toFixed(1)} с</small></div></button>)}</aside><section className="preview"><div className="preview-media">{media?.kind === 'video' && media.url ? <video controls src={media.url} /> : media?.thumbUrl ? <img src={media.thumbUrl} /> : <div className="preview-placeholder">Нет кадра</div>}</div><label className="subtitle-edit">Субтитр<textarea value={text} onChange={e => setText(e.target.value)} /></label><div className="timeline">{project.scenes.map((s, i) => <button key={s.id} onClick={() => select(i)} className={i === selected ? 'selected' : ''} style={{ flex: Math.max(1, s.endMs - s.startMs) }}>{i + 1}</button>)}</div></section><aside className="candidates"><h3>Кандидаты <span>{scene?.candidates?.length || 0}</span></h3>{(scene?.candidates || []).map((c, i) => <button className={scene.pick?.url === c.url ? 'candidate picked' : 'candidate'} key={c.url} onClick={async () => { const p = await api(`/projects/${id}/scenes/${scene.id}`, { method: 'PATCH', body: JSON.stringify({ pickIndex: i }) }); setProject(p); }}><img src={c.thumbUrl || c.url} /><div><b>{c.source}</b>{c.kind === 'video' && <span className="video-badge">VIDEO</span>}<small>{c.author || c.title || 'Открытая лицензия'}</small></div></button>)}</aside></div></div>;
}
